remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
title: 16S-qiime2R
subtitle: 
description: >- # this means to ignore newlines until "baseurl:"
  This is the demo site for a Jekyll theme version of
  HTML5 UP's sleek, responsive site template Prologue.
author: Yeva
email: yueshan@uchicago.edu

# You'll want to customize url and baseurl for your own site:
baseurl: "/notes"
url: "https://github.com/yue-shan/16S-qiime2R"
